package com.sh3h.localprovider.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.sh3h.localprovider.entity.History;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTORY".
*/
public class HistoryDao extends AbstractDao<History, Long> {

    public static final String TABLENAME = "HISTORY";

    /**
     * Properties of entity History.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Account = new Property(1, String.class, "account", false, "ACCOUNT");
        public final static Property TaskId = new Property(2, long.class, "taskId", false, "TASK_ID");
        public final static Property Type = new Property(3, int.class, "type", false, "TYPE");
        public final static Property SubType = new Property(4, int.class, "subType", false, "SUB_TYPE");
        public final static Property State = new Property(5, int.class, "state", false, "STATE");
        public final static Property HangUpState = new Property(6, int.class, "hangUpState", false, "HANG_UP_STATE");
        public final static Property DelayState = new Property(7, int.class, "delayState", false, "DELAY_STATE");
        public final static Property ReportType = new Property(8, int.class, "reportType", false, "REPORT_TYPE");
        public final static Property Assist = new Property(9, int.class, "assist", false, "ASSIST");
        public final static Property Content = new Property(10, String.class, "content", false, "CONTENT");
        public final static Property Reply = new Property(11, String.class, "reply", false, "REPLY");
        public final static Property ReplyTime = new Property(12, long.class, "replyTime", false, "REPLY_TIME");
        public final static Property UploadFlag = new Property(13, int.class, "uploadFlag", false, "UPLOAD_FLAG");
        public final static Property Extend = new Property(14, String.class, "extend", false, "EXTEND");
    }

    private DaoSession daoSession;

    private Query<History> history_HistoriesQuery;
    private Query<History> task_HistoriesQuery;

    public HistoryDao(DaoConfig config) {
        super(config);
    }
    
    public HistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ACCOUNT\" TEXT," + // 1: account
                "\"TASK_ID\" INTEGER NOT NULL ," + // 2: taskId
                "\"TYPE\" INTEGER NOT NULL ," + // 3: type
                "\"SUB_TYPE\" INTEGER NOT NULL ," + // 4: subType
                "\"STATE\" INTEGER NOT NULL ," + // 5: state
                "\"HANG_UP_STATE\" INTEGER NOT NULL ," + // 6: hangUpState
                "\"DELAY_STATE\" INTEGER NOT NULL ," + // 7: delayState
                "\"REPORT_TYPE\" INTEGER NOT NULL ," + // 8: reportType
                "\"ASSIST\" INTEGER NOT NULL ," + // 9: assist
                "\"CONTENT\" TEXT," + // 10: content
                "\"REPLY\" TEXT," + // 11: reply
                "\"REPLY_TIME\" INTEGER NOT NULL ," + // 12: replyTime
                "\"UPLOAD_FLAG\" INTEGER NOT NULL ," + // 13: uploadFlag
                "\"EXTEND\" TEXT);"); // 14: extend
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, History entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(2, account);
        }
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getType());
        stmt.bindLong(5, entity.getSubType());
        stmt.bindLong(6, entity.getState());
        stmt.bindLong(7, entity.getHangUpState());
        stmt.bindLong(8, entity.getDelayState());
        stmt.bindLong(9, entity.getReportType());
        stmt.bindLong(10, entity.getAssist());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(11, content);
        }
 
        String reply = entity.getReply();
        if (reply != null) {
            stmt.bindString(12, reply);
        }
        stmt.bindLong(13, entity.getReplyTime());
        stmt.bindLong(14, entity.getUploadFlag());
 
        String extend = entity.getExtend();
        if (extend != null) {
            stmt.bindString(15, extend);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, History entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(2, account);
        }
        stmt.bindLong(3, entity.getTaskId());
        stmt.bindLong(4, entity.getType());
        stmt.bindLong(5, entity.getSubType());
        stmt.bindLong(6, entity.getState());
        stmt.bindLong(7, entity.getHangUpState());
        stmt.bindLong(8, entity.getDelayState());
        stmt.bindLong(9, entity.getReportType());
        stmt.bindLong(10, entity.getAssist());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(11, content);
        }
 
        String reply = entity.getReply();
        if (reply != null) {
            stmt.bindString(12, reply);
        }
        stmt.bindLong(13, entity.getReplyTime());
        stmt.bindLong(14, entity.getUploadFlag());
 
        String extend = entity.getExtend();
        if (extend != null) {
            stmt.bindString(15, extend);
        }
    }

    @Override
    protected final void attachEntity(History entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public History readEntity(Cursor cursor, int offset) {
        History entity = new History( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // account
            cursor.getLong(offset + 2), // taskId
            cursor.getInt(offset + 3), // type
            cursor.getInt(offset + 4), // subType
            cursor.getInt(offset + 5), // state
            cursor.getInt(offset + 6), // hangUpState
            cursor.getInt(offset + 7), // delayState
            cursor.getInt(offset + 8), // reportType
            cursor.getInt(offset + 9), // assist
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // content
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // reply
            cursor.getLong(offset + 12), // replyTime
            cursor.getInt(offset + 13), // uploadFlag
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // extend
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, History entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTaskId(cursor.getLong(offset + 2));
        entity.setType(cursor.getInt(offset + 3));
        entity.setSubType(cursor.getInt(offset + 4));
        entity.setState(cursor.getInt(offset + 5));
        entity.setHangUpState(cursor.getInt(offset + 6));
        entity.setDelayState(cursor.getInt(offset + 7));
        entity.setReportType(cursor.getInt(offset + 8));
        entity.setAssist(cursor.getInt(offset + 9));
        entity.setContent(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setReply(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setReplyTime(cursor.getLong(offset + 12));
        entity.setUploadFlag(cursor.getInt(offset + 13));
        entity.setExtend(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(History entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(History entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(History entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "histories" to-many relationship of History. */
    public List<History> _queryHistory_Histories(long taskId) {
        synchronized (this) {
            if (history_HistoriesQuery == null) {
                QueryBuilder<History> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskId.eq(null));
                queryBuilder.orderRaw("T.'REPLY_TIME' DESC");
                history_HistoriesQuery = queryBuilder.build();
            }
        }
        Query<History> query = history_HistoriesQuery.forCurrentThread();
        query.setParameter(0, taskId);
        return query.list();
    }

    /** Internal query to resolve the "histories" to-many relationship of Task. */
    public List<History> _queryTask_Histories(long taskId) {
        synchronized (this) {
            if (task_HistoriesQuery == null) {
                QueryBuilder<History> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskId.eq(null));
                queryBuilder.orderRaw("T.'REPLY_TIME' DESC");
                task_HistoriesQuery = queryBuilder.build();
            }
        }
        Query<History> query = task_HistoriesQuery.forCurrentThread();
        query.setParameter(0, taskId);
        return query.list();
    }

}
