package com.sh3h.localprovider.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.sh3h.localprovider.entity.Temporary;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEMPORARY".
*/
public class TemporaryDao extends AbstractDao<Temporary, Long> {

    public static final String TABLENAME = "TEMPORARY";

    /**
     * Properties of entity Temporary.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Account = new Property(1, String.class, "account", false, "ACCOUNT");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property SubType = new Property(3, int.class, "subType", false, "SUB_TYPE");
        public final static Property State = new Property(4, int.class, "state", false, "STATE");
        public final static Property HangUpState = new Property(5, int.class, "hangUpState", false, "HANG_UP_STATE");
        public final static Property DelayState = new Property(6, int.class, "delayState", false, "DELAY_STATE");
        public final static Property ReportType = new Property(7, int.class, "reportType", false, "REPORT_TYPE");
        public final static Property Assist = new Property(8, int.class, "assist", false, "ASSIST");
        public final static Property Content = new Property(9, String.class, "content", false, "CONTENT");
        public final static Property Reply = new Property(10, String.class, "reply", false, "REPLY");
        public final static Property ReplyTime = new Property(11, long.class, "replyTime", false, "REPLY_TIME");
        public final static Property UploadFlag = new Property(12, int.class, "uploadFlag", false, "UPLOAD_FLAG");
        public final static Property Extend = new Property(13, String.class, "extend", false, "EXTEND");
    }

    private DaoSession daoSession;

    private Query<Temporary> history_TemporaryQuery;

    public TemporaryDao(DaoConfig config) {
        super(config);
    }
    
    public TemporaryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEMPORARY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ACCOUNT\" TEXT," + // 1: account
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"SUB_TYPE\" INTEGER NOT NULL ," + // 3: subType
                "\"STATE\" INTEGER NOT NULL ," + // 4: state
                "\"HANG_UP_STATE\" INTEGER NOT NULL ," + // 5: hangUpState
                "\"DELAY_STATE\" INTEGER NOT NULL ," + // 6: delayState
                "\"REPORT_TYPE\" INTEGER NOT NULL ," + // 7: reportType
                "\"ASSIST\" INTEGER NOT NULL ," + // 8: assist
                "\"CONTENT\" TEXT," + // 9: content
                "\"REPLY\" TEXT," + // 10: reply
                "\"REPLY_TIME\" INTEGER NOT NULL ," + // 11: replyTime
                "\"UPLOAD_FLAG\" INTEGER NOT NULL ," + // 12: uploadFlag
                "\"EXTEND\" TEXT);"); // 13: extend
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEMPORARY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Temporary entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(2, account);
        }
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getSubType());
        stmt.bindLong(5, entity.getState());
        stmt.bindLong(6, entity.getHangUpState());
        stmt.bindLong(7, entity.getDelayState());
        stmt.bindLong(8, entity.getReportType());
        stmt.bindLong(9, entity.getAssist());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(10, content);
        }
 
        String reply = entity.getReply();
        if (reply != null) {
            stmt.bindString(11, reply);
        }
        stmt.bindLong(12, entity.getReplyTime());
        stmt.bindLong(13, entity.getUploadFlag());
 
        String extend = entity.getExtend();
        if (extend != null) {
            stmt.bindString(14, extend);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Temporary entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(2, account);
        }
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getSubType());
        stmt.bindLong(5, entity.getState());
        stmt.bindLong(6, entity.getHangUpState());
        stmt.bindLong(7, entity.getDelayState());
        stmt.bindLong(8, entity.getReportType());
        stmt.bindLong(9, entity.getAssist());
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(10, content);
        }
 
        String reply = entity.getReply();
        if (reply != null) {
            stmt.bindString(11, reply);
        }
        stmt.bindLong(12, entity.getReplyTime());
        stmt.bindLong(13, entity.getUploadFlag());
 
        String extend = entity.getExtend();
        if (extend != null) {
            stmt.bindString(14, extend);
        }
    }

    @Override
    protected final void attachEntity(Temporary entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Temporary readEntity(Cursor cursor, int offset) {
        Temporary entity = new Temporary( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // account
            cursor.getInt(offset + 2), // type
            cursor.getInt(offset + 3), // subType
            cursor.getInt(offset + 4), // state
            cursor.getInt(offset + 5), // hangUpState
            cursor.getInt(offset + 6), // delayState
            cursor.getInt(offset + 7), // reportType
            cursor.getInt(offset + 8), // assist
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // content
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // reply
            cursor.getLong(offset + 11), // replyTime
            cursor.getInt(offset + 12), // uploadFlag
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13) // extend
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Temporary entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccount(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setSubType(cursor.getInt(offset + 3));
        entity.setState(cursor.getInt(offset + 4));
        entity.setHangUpState(cursor.getInt(offset + 5));
        entity.setDelayState(cursor.getInt(offset + 6));
        entity.setReportType(cursor.getInt(offset + 7));
        entity.setAssist(cursor.getInt(offset + 8));
        entity.setContent(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setReply(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setReplyTime(cursor.getLong(offset + 11));
        entity.setUploadFlag(cursor.getInt(offset + 12));
        entity.setExtend(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Temporary entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Temporary entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Temporary entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "temporary" to-many relationship of History. */
    public List<Temporary> _queryHistory_Temporary(Long id) {
        synchronized (this) {
            if (history_TemporaryQuery == null) {
                QueryBuilder<Temporary> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Id.eq(null));
                history_TemporaryQuery = queryBuilder.build();
            }
        }
        Query<Temporary> query = history_TemporaryQuery.forCurrentThread();
        query.setParameter(0, id);
        return query.list();
    }

}
